FROM eclipse-temurin:21-jdk
WORKDIR /app

# Copiar el Maven Wrapper
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

# Dar permisos de ejecución al wrapper
RUN chmod +x mvnw

# Descargar dependencias (esta capa se cachea si pom.xml no cambia)
RUN ./mvnw dependency:go-offline -B

# Copiar el código fuente
COPY src ./src
EXPOSE 8081

# Comando para desarrollo con perfil docker
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=docker"]