ALTER TABLE agrosys_worker.WORKER
    ADD COLUMN salary DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN photo LONGTEXT NULL;

ALTER TABLE agrosys_worker.WORKER
    MODIFY COLUMN notas VARCHAR(255) NULL;