spring.application.name=agrosys-auth

# Puerto del servidor
server.port=8083

# Configuración de la base de datos (USA VARIABLES DE ENTORNO)
spring.datasource.url=${DB_URL_AUTH:jdbc:mysql://localhost:3307/agrosys_auth?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=${JWT_SECRET:Akm5aG9836Rl98PO982u2S671Y2026ewkSsecretKeyAppT0w3nt1c4c10nrtows6ddw}
jwt.expiration=${JWT_EXPIRATION:86400000}

#Health Check
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.com.agrosys=DEBUG
logging.level.org.springframework.security=DEBUG
# Patrón de log para consola
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - [%-5level] [%logger{36}.%M:%L] - %msg%n

spring.devtools.restart.enabled=true

