spring.application.name=agrosys-web

server.port=8081

server.servlet.context-path=/agrosys

gateway.base-url=http://agrosys-gateway:8080

# JWT
jwt.secret=${JWT_SECRET:Akm5aG9836Rl98PO982u2S671Y2026ewkSsecretKeyAppT0w3nt1c4c10nrtows6ddw}

spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true

# Logging
logging.level.com.agrosys=DEBUG
logging.level.org.springframework.security=DEBUG
# Patrón de log para consola
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - [%-5level] [%logger{36}.%M:%L] - %msg%n



