spring.application.name=agrosys-web

server.port=8081

gateway.base-url=http://agrosys-gateway:8080

# JWT
jwt.secret=${JWT_SECRET:Akm5aG9836Rl98PO982u2S671Y2026ewkSsecretKeyAppT0w3nt1c4c10nrtows6ddw}

spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true

